spring.application.name=demo
server.port=8080

spring.datasource.url = jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0


spring.datasource.username = postgres.upfrofppponiqffbssqb
spring.datasource.password = 6UVt2zz2iwSPcvqE
spring.datasource.driver-class-name = org.postgresql.Driver


spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=uploads/

spring.ai.google.genai.api-key=AIzaSyCyp89l3RW5jR64xt08g_wZOAWVDTG3cpc
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
spring.ai.google.genai.chat.options.temperature=0.7
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=barangay.admin.sansebastian.gov.ph@gmail.com
spring.mail.password=pidz rsjy snqt ytkh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoint.health.show-details=always